{% set version = "0.3.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rhandsontable
  version: {{ version|replace("-", "_") }}

source:
  fn: rhandsontable_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rhandsontable_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rhandsontable/rhandsontable_{{ version }}.tar.gz
  sha256: 088eb17c0727bc4b8e500c59d517b81cd281dfa97ec2fb4097579516ffa5cdf8

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-htmlwidgets >=0.3.3
    - r-jsonlite
    - r-magrittr
  run:
    - r-base
    - r-htmlwidgets >=0.3.3
    - r-jsonlite
    - r-magrittr

test:
  commands:
    - $R -e "library('rhandsontable')"           # [not win]
    - "\"%R%\" -e \"library('rhandsontable')\""  # [win]

about:
  home: http://jrowen.github.io/rhandsontable/
  license: MIT
  summary: An R interface to the 'Handsontable' JavaScript library, which is a minimalist Excel-like
    data grid editor.  See <https://handsontable.com/> for details.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
