{% set version = "0.3.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rhandsontable
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rhandsontable_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rhandsontable/rhandsontable_{{ version }}.tar.gz
  sha256: 901ed9c59936f7fa52ad8db3111c8904ab962f9c74f1b6cd40f81683af35d21d

build:
  number: 4
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-htmlwidgets >=0.3.3
    - r-jsonlite
    - r-magrittr
  run:
    - r-base
    - r-htmlwidgets >=0.3.3
    - r-jsonlite
    - r-magrittr

test:
  commands:
    - $R -e "library('rhandsontable')"           # [not win]
    - "\"%R%\" -e \"library('rhandsontable')\""  # [win]

about:
  home: http://jrowen.github.io/rhandsontable/
  license: MIT
  summary: An R interface to the 'Handsontable' JavaScript library, which is a minimalist Excel-like data grid editor.  See <https://handsontable.com/> for details.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
