# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RFJWNjZ1RWxHIH6jHK2u3lAr2F5VEs4cOGU5cxH907CZtfuYcjw3JQ7SxE2CCfK/yhnBxyqSKENqW+kokJnQPTXLBCPT4LVoAA51FNTuzWjIJWXUEQ6TL0olU9gtPnFGzTg42ou9nmoetHogjLSOUccWh/3IIvWzI1xBCpGGfjTJjvwzstDAk3yxuGW9B3JRy/8jpfv/Q/7c9UfRS7NiAzzjQ6JIJ1KdoBtBgd61/V4yDu+Z2E+SEwu1XZXVinkYtPZ04YrPN6wQEiWMuKtQRHWI0494zxMkbTCJm7N4s3dOgNJE5iIkrKlSxIEt1q36Q/nq2CvotYBCA108mjglSbyX5uD8D9WOWrYkAXjlIYFMSXcvG0zKvJfJys0SPi8SPA+D2s6XAGUFnr9u/u3WRVv7OgwFoL1a3h0VVVUMnCpVlwJmj4LPfCRzMld+hRzXWYPkf4OKnHUugz10dwh+OJtewcMR25A3w7xqMuWgVq8MiW4L1xUpyGZm2SMWLTDDENXYS+d2RxDw2msek7NDJ3kGfaI4hQtoqaq/9iUnvl/C3MqYW7l0oFoCCSuxnRNPwwzEGCIT38xc54lyfXDdF6YOmsKwHPDmRbuH84AP1h2BLqpNMgF1kDOeesLHdpy7ZPljIT6uS98ahexyziAiqkj1tuay3RYim9t2s/wtulw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
