travis:
  secure:
    BINSTAR_TOKEN: T5edIw5x+a78v/B1Ds66FgooSDzNBajEpsRQ0k4Q5IcpVn/zwTQHki5u2QQ9ar792KEEzc+PkFvylf02zIC6TEUHPdwiR2nJhmDGtGjNMPM680kf3Ozpgz5UfkppROxcnoq2K+Ag8y6jCxn6G2sATwMc9gqnIMy6vJ5qKBrB8XzTIl6VQXXIx08uHHqwUCw3awFiWFo4d8Z2SHHr098ENx44QhnCkXA/MI1ouvUMRbF1G0PPO3il06XWrbi7eyqVf3W+7TB7XEtD6V5ymmrCUWqzAhB6kqnz9czzkWuxjvEOgPOoqk9tgQh11eqNYhFW/lDnBWuPx9TAbav2Y3czjsSBfsiTs3SnVnXdcwEArjbdwGRZUro1zj7zU8n+lS8ANkDMhJOP4/MTv56mnbZde+gBFg9EHFKcwGddxlCLpaJZkO+cTly3sOCmsg/lXquqzCYtebluHu2bgb8GMnEL93pCP8g/HhECHbBsaQtFoGJcP3Y/el38hfK4Yg1xFzZiIeoXnA87ZxjBUt8D+y2bkcLtrRS5vTseNeiRF8GW69ZvkOKTbukoQQBPYF4iB/WQJhQ6E+Hzf4gIDypef+dFcnZbzClVwHcHabw+EdJv4YjENurdvrn71H8DQQGouDs/stNgpU+TGGTrMDZwT3WBwGcCgzbEjrOfPwkVlkIEnQ8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
