travis:
  secure:
    BINSTAR_TOKEN: RFJWNjZ1RWxHIH6jHK2u3lAr2F5VEs4cOGU5cxH907CZtfuYcjw3JQ7SxE2CCfK/yhnBxyqSKENqW+kokJnQPTXLBCPT4LVoAA51FNTuzWjIJWXUEQ6TL0olU9gtPnFGzTg42ou9nmoetHogjLSOUccWh/3IIvWzI1xBCpGGfjTJjvwzstDAk3yxuGW9B3JRy/8jpfv/Q/7c9UfRS7NiAzzjQ6JIJ1KdoBtBgd61/V4yDu+Z2E+SEwu1XZXVinkYtPZ04YrPN6wQEiWMuKtQRHWI0494zxMkbTCJm7N4s3dOgNJE5iIkrKlSxIEt1q36Q/nq2CvotYBCA108mjglSbyX5uD8D9WOWrYkAXjlIYFMSXcvG0zKvJfJys0SPi8SPA+D2s6XAGUFnr9u/u3WRVv7OgwFoL1a3h0VVVUMnCpVlwJmj4LPfCRzMld+hRzXWYPkf4OKnHUugz10dwh+OJtewcMR25A3w7xqMuWgVq8MiW4L1xUpyGZm2SMWLTDDENXYS+d2RxDw2msek7NDJ3kGfaI4hQtoqaq/9iUnvl/C3MqYW7l0oFoCCSuxnRNPwwzEGCIT38xc54lyfXDdF6YOmsKwHPDmRbuH84AP1h2BLqpNMgF1kDOeesLHdpy7ZPljIT6uS98ahexyziAiqkj1tuay3RYim9t2s/wtulw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
