travis:
  secure:
    BINSTAR_TOKEN: lC2s8a0VBB+em7PsMfEdpBT4z1tv1yiZtKDlNB4BfZYP+VjW0fomAva9Omz82+afx2olW8ws/dg7o2Xa3GKXmjrzJhvMRuo0Zq3iHVhkLUwmRU9+JZmOamZTkrvVnLKdf+gNyGLnuVeNTbze9ygrri5JyOj57pPyqVp7xTODeRxKiHx4mRc0ATeu1ksyWb25RLf+XTW1serGPfhOH45HRUo/d/JUSrgdm+NH/FXplXgaRMFqZYmU+uMMMwHbt1IGoVV03oVRueooUgLLD01vvH2zlrDCuF4WBtGAoCFqM40UyONxSvCygai+N/praThHY9vR+mPoafmzIc3QuU/OV7Eu1Yft+oFKx/k7e32BZeif7PEvOKHOPPJS+pKQAtMJwdnaqNWl0romIZAyFDeTWN90DvCXm325HCiK4Nu7SynrnatYeWgWC/Xnn4/VVDDidqiIX9WTvhXAZ0zhWLdBu47UXITH6675OTOxiW5yEa7XaGBItSaqIrwGK83gJo7geR1gZ68gNOrJEP/cm7SfE3FJN0w/K/859/wUmr/k5J+PsXiT61lvqLqPa/HzctyYgfF4/gLWKFEkA8WrsiwJYS1jWPqkckkhCT7ZIFIK9nDvSlp7OZxI9cbcN8KBTNmCkjWggjDmGMEKpWjs2erX2wRwNwri/KZKuyKzDVROH70=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
